AllCops:
  Exclude:
    - Gemfile
    - spec/**/**
    - Rakefile
    - rakelib/**/**
    - log_formatter.gemspec
    - bin/*

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false